### ISSUE TITLE
[ERROR] Cloudflare Bypass gk berfungsi.

### ISSUE THREAD

**Issue by BayuSJW** [Bandhitawkunthi/TawkunDoS#1]
### Cloudflare Bypass gk berfungsi
Sama sekali gk nge-Bypass Cloudflare. udah dicoba di website saya sendiri ([AwSakit](https://www.awsakit.ga)), tetap walaupun pakai Proxy/SOCKS.

### Spesifikasi Device
• Ubuntu 20.04

**Comment by Bandhitawkunthi** [comment]
Cmn bisa yang cloudflare free

**Comment by BayuSJW** [comment]
> Cmn bisa yang cloudflare free

iya, gw pake yang free.

**Comment by BayuSJW** [comment]
kesimpulannya isi script ini ga ada bypassnya sama sekali, jauh banget ekspetasinya sama yang di youtube.

**Comment by Bandhitawkunthi** [comment]
Cuma bisa bypass cloudflare free aja ingat!
